services:

  db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_NAME}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - sensedia:/var/lib/portgresql/data
    

  
  server:
    build: ./manager
    restart: always
    container_name: django-server
    env_file: ".env"
    ports:
      - "8000:8000"
    depends_on:
      - db
  

volumes:
  sensedia:

